### ISSUE TITLE
What is JCQZQBgZwY4S0e*KbxU

### ISSUE THREAD

**Issue by mhulse** [BetterBrief/vagrant-skeleton#137]
https://github.com/BetterBrief/vagrant-skeleton/blob/df11e57b9281fc6ab440357e078dbd79d091b96b/scripts/mysql-57.sh#L24

I'm trying to refresh my memory ... What is `JCQZQBgZwY4S0e*KbxU`?

Every time I see this line, I have to google what's going on here ... Just curious if anyone can fill me in as googling is not helping me at this moment. 😆

**Comment by dhensby** [comment]
Gah - that's a good question.

It looks like I copied out a temp password that should have been `${PASSWORD}`

I guess no one uses mysql5.7 on this repo!

**Comment by dhensby** [comment]
oh, wait, no - it looks like I'm setting the the users password to something that is known

**Comment by dhensby** [comment]
Yep, OK.

So this changes the current users password from the temp password to something that matches the validation rules. It then removes the password validator and sets the users password to nothing.

**Comment by mhulse** [comment]
Thank you for looking into that and for the code update!

I think the additional comments will be of great help for future readers of the code. 👍 :octocat: 

Have an excellent weekend. ;)
