### ISSUE TITLE
Sporadic httpd startup issues on vagrant up

### ISSUE THREAD

**Issue by jyrkij** [BetterBrief/vagrant-skeleton#27]
When I restart the box (without provisions) httpd doesn't start up. `chkconfig --list httpd` shows this:

```
httpd           0:off   1:off   2:on    3:on    4:on    5:on    6:off
```

so httpd should start. After some googling I saw [this](http://forums.fedoraforum.org/showthread.php?t=247541#post1376414). It seems to be exactly the problem I'm having. No log files display anything interesting. If I run `service httpd start` from an ssh session httpd starts normally.

Now to the problem. Having the docroot `/var/www/html` symlinked to `/vagrant/www` (or anything under `/vagrant`) might be the cause. httpd fails to start if it cannot find docroot. The symlink destination doesn't exist until later in the boot process when Vagrant mounts synced folders.

Could we instead keep the original /var/www/html and mount `www` under our project directory as [Vagrant Synced Folder](http://docs.vagrantup.com/v2/synced-folders/basic_usage.html)? This way, I believe, httpd would be able to start. But does mounting the synced folder work correctly with httpd? I haven't had time to test this theory in practice.

**Comment by kenorb** [comment]
See: [Apache doesn't start after Vagrant reload](http://stackoverflow.com/q/22718785/55075) at SO

**Comment by dhensby** [comment]
I think my solution is simple enough. Thanks for the link, though
