### ISSUE TITLE
Nginx

### ISSUE THREAD

**Issue by Firesphere** [BetterBrief/vagrant-skeleton#55]
Could you add an Nginx initialisation to replace Apache?

**Comment by willmorgan** [comment]
PRs welcome

**Comment by dhensby** [comment]
It's not something I'm considering adding at the moment as my experience with nginx is limited. However, I would review and consider PRs...

**Comment by Firesphere** [comment]
I only use Nginx nowadays. Should I include a default config for SilverStripe? Because the basic configs for e.g. Symfony and Laravel are different.

**Comment by willmorgan** [comment]
I think this would probably have to be a fork, unless we do some sort of composer create project deal.

**Comment by Firesphere** [comment]
I'm not entirely sure if I understand what you mean @willmorgan You mean I should create a fork, where I maintain the nginx+FPM installations? (That's no problem btw, just not sure what exactly you mean ;) )

**Comment by willmorgan** [comment]
I think you can ask a dev for their preferences when it comes to server software when creating, using composer create-project. Might be wrong though.

I do think that a fork might be better in this instance. @dhensby thoughts?

**Comment by dhensby** [comment]
managing a fork would be a pain for everyone imo.

I'd take an nginx installer. our apache installer is actually a "install apache and silverstripe" so no reason an nginx script couldn't be a drop in replacement?

**Comment by Firesphere** [comment]
Ok, I'll get to work on my default Nginx setup to at least support the passthrough to PHP etc.

It would require PHP-FPM, but I'm not a fan of installing FPM when using Apache, that's the biggest issue to fix in this. Other than that, it's pretty straight forward.

**Comment by dhensby** [comment]
Any luck on this @Firesphere ?

**Comment by Firesphere** [comment]
Got it working, but nothing substantial yet, not something worthy of publishing.

**Comment by dhensby** [comment]
ok
