### ISSUE TITLE
HHVM

### ISSUE THREAD

**Issue by Firesphere** [BetterBrief/vagrant-skeleton#56]
Is it possible to add HHVM as the PHP interpreter, instead of the given PHP versions?

**Comment by willmorgan** [comment]
PRs welcome

**Comment by Firesphere** [comment]
To both, I know ;) But just opening the issue so it's at least somewhere documented :) I just started trying this Vagrant machine you guys are using :)

**Comment by dhensby** [comment]
Yes, I'd like to do this.

Relevant: https://github.com/facebook/hhvm/wiki/Building-and-installing-hhvm-on-CentOS-7.x

**Comment by dhensby** [comment]
HHVM is superseded by PHP 7 now IMO
