### ISSUE TITLE
Option: Empty the /vagrant/www/silverstripe-cache directory

### ISSUE THREAD

**Issue by Firesphere** [BetterBrief/vagrant-skeleton#65]
This way, at least you are sure, everytime you start the machine, the cache is emptied. If you agree to this idea, I'll create a pull-request.

This doesn't work when there's no silverstripe-cache defined, so the direcotry will be also created in the silverstripe tasks script.

Possibly build and flush in the task?

**Comment by dhensby** [comment]
For the ss-tasks? yes, we could clear the cache like this, I don't see why not.

```bash
if [ -d /vagrant/www/silverstripe-cache ]; then
    rm -rf /vagrant/www/silverstripe-cache/*
fi
```
