### ISSUE TITLE
Silverstripe Tasks assumes www

### ISSUE THREAD

**Issue by Firesphere** [BetterBrief/vagrant-skeleton#66]
In silverstripe tasks script, the directory /vagrant/www is assumed, while the database and apache scripts scan for commonly known directories. Things could break due to this.

**Comment by dhensby** [comment]
Good spot

**Comment by dhensby** [comment]
Hmm, I just took a look. It assumes that the webroot is `/var/www/html` not that it's `/vagrant/www`.

No matter what the webroot in the project dir, it'll be symlinked to `/var/www/html` so this is the most robust way of doing it...
