### ISSUE TITLE
HeidiSQL exports fail and leave an empty database

### ISSUE THREAD

**Issue by Firesphere** [BetterBrief/vagrant-skeleton#67]
Most probably, this is a bug in HeidiSQL, but maybe there's a workaround possible. I'll also have a look if I can find a reason what causes this.

**Comment by dhensby** [comment]
Most likely - I've had no issue with MySQL workbench

**Comment by Firesphere** [comment]
It seems Heidi uses an opening comment or call not recognized by the mysql terminal method.

Despite the issue being not on the side of the scripts, I'll have a look if I can fix it, because Heidi is quite nice to work with (Personal opinion), but don't expect a PR about it soon. It's quite low on my list of todo.

**Comment by dhensby** [comment]
@Firesphere any progress with this or should I close this?

**Comment by Firesphere** [comment]
I have not yet taken my time to have a look at it. Given I have a lot of spare time right now, I intended to have a look at what exactly goes wrong this week..
