### ISSUE TITLE
dev/build times out

### ISSUE THREAD

**Issue by Firesphere** [BetterBrief/vagrant-skeleton#77]
I suggest raising the max_execution_time to 90 seconds.

**Comment by dhensby** [comment]
Good point; though this is highly dependent on host machine hardware capabilities.

this will do the job `sed -i 's/max_execution_time.*/max_execution_time = 90/g' /etc/php.ini` though we should be careful it doesn't bring down someone elses customisation.

**Comment by Firesphere** [comment]
I doubt setting it to 90 seconds will take down a decent development machine. If it does.... It's not really a devmachine now, is it?

**Comment by dhensby** [comment]
this will be very easy to add now that the PHP script is unified (see #101)

We just need to add a parameter (`-e` I'd go for) and then run the above `sed` command and we're done.
