### ISSUE TITLE
Repository ownership

### ISSUE THREAD

**Issue by willmorgan** [BetterBrief/vagrant-skeleton#79]
Now that BB is finished, should we be moving this to another user/organisation? Possibly SilverStripe?

**Comment by Firesphere** [comment]
I don't think SilverStripe will take it, they have their own box if I'm not mistaken.

**Comment by dhensby** [comment]
I'm happy to keep maintaining it (here) though ownership could be changed to me?! I don't see an advantage in that...

Does GitHub 301 ownership changes like it does repo renaming?

**Comment by willmorgan** [comment]
Just seeking clarification on the ownership of BB's open source projects.

**Comment by dhensby** [comment]
They remain in the public domain and maintained by a few volunteers :)
