### ISSUE TITLE
Running yum update breaks the mounting of the vagrant directory.

### ISSUE THREAD

**Issue by Firesphere** [BetterBrief/vagrant-skeleton#81]
This is fixed by running the following commands on the box, then reloading it:
```
sudo yum install kernel-devel-$(uname -r) kernel-headers-$(uname -r) dkms -y
sudo /etc/init.d/vboxadd setup
```
Maybe an option to add this to the "always" script?

**Comment by dhensby** [comment]
interesting.. Is this just running `yum update` that breaks? I haven't experienced it as I don't typically run an unrestricted update.

**Comment by dhensby** [comment]
If you explain a bit what's going on in this patch and add it to the always script, I'd take it in.

Though, does it need to run on every boot and/or wakeup or just on initial provision?

**Comment by Firesphere** [comment]
It only breaks when yum update is ran from the SSH terminal. So I'm doubting it should be ran always, maybe just added to the readme would suffice probably?

**Comment by dhensby** [comment]
So I've replicated but when I run your patch I get "no package dkms found" - but the fix still works.

I'm happy to put this in the bootstrap, it'll save people pain.
