### ISSUE TITLE
More power!

### ISSUE THREAD

**Issue by Firesphere** [BetterBrief/vagrant-skeleton#82]
How do I give the box more power? I have 8 cores on my dev-machine, and 64GB of RAM. I think 1 core and 512MB is a bit low for me.

How can I increase the box's power to e.g. 2 cores and 2G of RAM?

**Comment by willmorgan** [comment]
http://docs.vagrantup.com/v2/virtualbox/configuration.html

> VBOXMANAGE CUSTOMIZATIONS

```
config.vm.provider "virtualbox" do |v|
  v.memory = 1024
  v.cpus = 2
end
```

**Comment by Firesphere** [comment]
I am an idiot :F
