### ISSUE TITLE
Grunt fails to install on shared dir

### ISSUE THREAD

**Issue by dhensby** [BetterBrief/vagrant-skeleton#91]
I keep getting errors on the grunt installer (via provisioner or by hand) when installing on a mounted folder; this is a PITA.

**Comment by dhensby** [comment]
Ok, this is what `--no-bin-links` is for. So I've probably mis-identified the problem...

**Comment by willmorgan** [comment]
Yes, npm on Windows (or via vagrant) is terrible.

**Comment by dhensby** [comment]
I think this is mostly me just not understanding shit about npm / grunt.

I'm going to close this off...
