### ISSUE TITLE
SASSC exits with error 11

### ISSUE THREAD

**Issue by Firesphere** [BetterBrief/vagrant-skeleton#98]
Any advice on how to fix this error?
```
[User Error] Uncaught Symfony\Component\Process\Exception\RuntimeException: The process has been signaled with signal "11".
GET /?flushtoken=47f5529f874c0d4f3ccb4471d77cb581&flush=all

Line 367 in /vagrant/www/vendor/symfony/process/Process.php
```
I can't find what's wrong, since it's my local Vagrant box with full rights.

**Comment by dhensby** [comment]
What are you trying to do that causes this error?

**Comment by Firesphere** [comment]
It seems the fallback doesn't work when it's not having a parent. It was an SASSC issue on CentOS, not related to the box itself. Took me a while to figure out.

**Comment by dhensby** [comment]
OK good stuff!
